name: app_center
description: Visual Studio App Center plugin for Flutter applications.
version: 0.3.0
authors: 
  - Aloïs Deniel<alois.deniel@outlook.com>
  - Damien Aicheh<damien.aicheh@gmail.com>
homepage: https://github.com/aloisdeniel/flutter_plugin_appcenter

environment:
  sdk: ">=3.5.3 <4.0.0" 
  
dependencies:
  flutter:
    sdk: flutter
flutter:
  plugin:
    androidPackage: com.aloisdeniel.flutter.app_center
    pluginClass: AppcenterPlugin